image: python:3.9

clone:
  depth: full  # SonarQube Cloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache # Caching SonarQube Cloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarQube Cloud
        caches:
          - sonar
        script:
          # Check if there are any Python file changes
          - |
            if git diff --name-only origin/$BITBUCKET_PR_DESTINATION..HEAD | grep -E '\.py$'; then
              echo "Python files changed, running SonarCloud scan..."
              pipe: sonarsource/sonarcloud-scan:3.0.0
            else
              echo "No Python file changes detected. Skipping SonarCloud scan."
            fi
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarQube Cloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
  branches:
    master:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
