image: node:22

pipelines:
  branches:
    WW-93-development-create-development-branch-with-standard-file-structure:
      - step:
          name: Deploy to Firebase Hosting
          script:
            - npm install -g firebase-tools
            - firebase deploy --token="$FIREBASE_TOKEN" --project="whichway-9040f"
  pull-requests:
    '**':
      - step:
          name: Install Dependencies and Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
