  Fixing-missed-assets-from-63[m
  Vinny-readme-changes[m
  WW-31-task-2-create-ui-wireframes[m
  WW-32-task-3-implement-frontend[m
  WW-37-task-2-implement-navigation-and-la[m
  WW-37_MergeTestWith_WW-6[m
  WW-38-task-3-develop-interactive-ui-elem[m
  WW-42-task-2-cleaning-duplicates[m
* [32mWW-43-task-3-fix-trip-id-issue[m
  WW-5-task-2-implement-authentication[m
  WW-54-task-3-refactor-create-trip-page[m
  WW-54-task-3-refactor-create-trip-page-2nd-try[m
  WW-65-task-2-frontend-input-for-budget-a[m
  WW-66-task-3-storing-budgets-and-costs[m
  WW-67-budget-error-validation-post-activities-change[m
  WW-67-task-4-budget-validation-and-error[m
  WW-68-task-5-error-handling-and-integration[m
  WW-73-task-2[m
  WW-73-task-2-implement-backend-api-for-trip-management[m
  WW-93-development-create-development-branch-with-standardized-file-structure[m
  WW-94-create-file-that-holds-console-commands[m
  development[m
  help[m
  main[m
